import type { FlowNodeData } from './types';

export const COLORS = {
  background: '#0a0a1a',
  backgroundEnd: '#1a0a2a',
  anthropic: '#ff6b35',
  openai: '#00d9a3',
  translation: '#a855f7',
  streaming: '#ffd700',
  error: '#ff3366',
  success: '#00ff88',
  text: '#ffffff',
  textDim: '#a0a0c0',
  cardBg: 'rgba(20, 20, 40, 0.8)',
  border: 'rgba(168, 85, 247, 0.3)',
};

export const FLOW_NODES: FlowNodeData[] = [
  {
    id: 'client',
    type: 'client' as const,
    title: 'Client Request',
    subtitle: 'POST /v1/messages',
    color: '#60a5fa',
    glowColor: 'rgba(96, 165, 250, 0.6)',
    icon: '📱',
    details: ['Claude Code CLI', 'Codex CLI', 'Any Anthropic/OpenAI client'],
  },
  {
    id: 'server',
    type: 'server' as const,
    title: 'HTTP Server :8080',
    subtitle: 'GoZen ServeMux',
    color: '#3b82f6',
    glowColor: 'rgba(59, 130, 246, 0.6)',
    icon: '🌐',
    details: ['10MB body limit', 'Goroutine per request', 'Context propagation'],
  },
  {
    id: 'router',
    type: 'router' as const,
    title: 'Smart Router',
    subtitle: 'getProviderChain()',
    color: '#a855f7',
    glowColor: 'rgba(168, 85, 247, 0.6)',
    icon: '🧠',
    details: ['Format-aware priority', 'Auto-fallback chain', 'Zero IPC'],
  },
  {
    id: 'keypool',
    type: 'keypool' as const,
    title: 'Key Pool',
    subtitle: 'Round-robin + Cooldown',
    color: '#f59e0b',
    glowColor: 'rgba(245, 158, 11, 0.6)',
    icon: '🔑',
    details: ['Thread-safe mutex', 'Per-key cooldown (60s)', 'Usage/failure tracking'],
  },
  {
    id: 'provider-zen',
    type: 'provider' as const,
    title: 'Provider 1: OpenCode Zen',
    subtitle: 'Anthropic format — direct',
    color: '#ff6b35',
    glowColor: 'rgba(255, 107, 53, 0.6)',
    icon: '⚡',
    details: ['Direct passthrough', 'No translation overhead', 'Priority: 1st'],
  },
  {
    id: 'translation',
    type: 'translation' as const,
    title: 'Translation Layer',
    subtitle: 'Anthropic ↔ OpenAI',
    color: '#a855f7',
    glowColor: 'rgba(168, 85, 247, 0.6)',
    icon: '🔄',
    details: [
      'System prompt → first message',
      'Content blocks → string',
      'input_schema → parameters',
      'Model mapping via model_map',
    ],
  },
  {
    id: 'provider-go',
    type: 'provider' as const,
    title: 'Provider 2: OpenCode Go',
    subtitle: 'OpenAI format — translated',
    color: '#00d9a3',
    glowColor: 'rgba(0, 217, 163, 0.6)',
    icon: '⚡',
    details: ['Requires translation', 'SSE stream conversion', 'Priority: 2nd'],
  },
  {
    id: 'provider-or',
    type: 'provider' as const,
    title: 'Provider 3: OpenRouter',
    subtitle: 'Free model fallback',
    color: '#00d9a3',
    glowColor: 'rgba(0, 217, 163, 0.6)',
    icon: '⚡',
    details: ['mistral-7b:free', 'llama-3.1-8b:free', 'gemma-2-9b:free', 'Priority: 3rd (last resort)'],
  },
  {
    id: 'sse',
    type: 'sse' as const,
    title: 'SSE Stream Translation',
    subtitle: 'Real-time line-by-line',
    color: '#ffd700',
    glowColor: 'rgba(255, 215, 0, 0.6)',
    icon: '📡',
    details: [
      'delta.content → text_delta',
      'finish_reason → stop_reason',
      '[DONE] → message_stop',
      'Flusher after every chunk',
    ],
  },
  {
    id: 'response',
    type: 'response' as const,
    title: 'Client Response',
    subtitle: 'Streaming tokens delivered',
    color: '#00ff88',
    glowColor: 'rgba(0, 255, 136, 0.6)',
    icon: '✅',
    details: ['Client never knows translation occurred', 'Real-time token delivery'],
  },
];
